name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

env:
  account_id: ${{ secrets.ACCOUNT_ID }}
  api_token: ${{ secrets.API_TOKEN }}

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    if: github.repository_owner == 'hasundue'
    needs: test
    uses: ./.github/workflows/release.yml
